### ISSUE TITLE
How to stop the lidar after running the example?

### ISSUE THREAD

**Issue by afonsofonbraga** [Livox-SDK/Livox-SDK2#11]
I couldn't find a way to make the lidar's motor to stop running after finishing the data acquisition. What is the best solution to do it via software and not by turning the lidar off manually?

**Comment by ZhenpengChenCode** [comment]
Same question

**Comment by Livox-Infra** [comment]
hi @afonsofonbraga @ZhenpengChenCode , 
For HAP or MID-360, try use API 'SetLivoxLidaWorkMode' to set lidar work mode to 0x02 (standby mode), pls refer to [livox_lidar_api.h](https://github.com/Livox-SDK/Livox-SDK2/blob/master/include/livox_lidar_api.h)

**Comment by Livox-Infra** [comment]
> 

So sorry about that, indeed such 'wrong name' inherited from an older version of communication protocol. We would fix it soon.

**Comment by NHMMing** [comment]
hi, @afonsofonbraga @Livox-Infra could you tell me how to use API 'SetLivoxLidaWorkMode' to set lidar work mode to 0x02 by using Livox-SDK2. I just saw  "SetLivoxLidarWorkMode(handle, kLivoxLidarNormal, WorkModeCallback, nullptr);" in function "void LidarInfoChangeCallback(const uint32_t handle, const LivoxLidarInfo *info, void *client_data)".However, I do not know how to use this api  correctly to stop my HAP lidar.

**Comment by hopenessQAQ** [comment]
> hi, @afonsofonbraga @Livox-Infra could you tell me how to use API 'SetLivoxLidaWorkMode' to set lidar work mode to 0x02 by using Livox-SDK2. I just saw "SetLivoxLidarWorkMode(handle, kLivoxLidarNormal, WorkModeCallback, nullptr);" in function "void LidarInfoChangeCallback(const uint32_t handle, const LivoxLidarInfo *info, void *client_data)".However, I do not know how to use this api correctly to stop my HAP lidar.

You know how to fix it?

**Comment by afonsofonbraga** [comment]
> > hi, @afonsofonbraga @Livox-Infra could you tell me how to use API 'SetLivoxLidaWorkMode' to set lidar work mode to 0x02 by using Livox-SDK2. I just saw "SetLivoxLidarWorkMode(handle, kLivoxLidarNormal, WorkModeCallback, nullptr);" in function "void LidarInfoChangeCallback(const uint32_t handle, const LivoxLidarInfo *info, void *client_data)".However, I do not know how to use this api correctly to stop my HAP lidar.
> 
> You know how to fix it?
 `SetLivoxLidarWorkMode(handle, kLivoxLidarWakeUp, WorkModeCallback, nullptr);` The 'kLivoxLidarWakeUp' does the trick, the variable name is wrong...

**Comment by NHMMing** [comment]
> @hopenessQAQ @NHMMing
> 
> > > hi, @afonsofonbraga @Livox-Infra could you tell me how to use API 'SetLivoxLidaWorkMode' to set lidar work mode to 0x02 by using Livox-SDK2. I just saw "SetLivoxLidarWorkMode(handle, kLivoxLidarNormal, WorkModeCallback, nullptr);" in function "void LidarInfoChangeCallback(const uint32_t handle, const LivoxLidarInfo *info, void *client_data)".However, I do not know how to use this api correctly to stop my HAP lidar.
> > 
> > 
> > You know how to fix it?
> > `SetLivoxLidarWorkMode(handle, kLivoxLidarWakeUp, WorkModeCallback, nullptr);` The 'kLivoxLidarWakeUp' does the trick, the variable name is wrong...

hello, do u know how to stop lidar by using apis? could u give me some suggestions?

**Comment by claudiomla** [comment]
If you wish to use it outside the callback functions, store the handle value in a global variable and simply call the function from anywhere in your code.

auto status = SetLivoxLidarWorkMode(handle_copy, kLivoxLidarWakeUp, WorkModeCallback, nullptr);

That is all.

But my question is: **How can I obtain the handle variable independently of any callback?**  Or, **how can I invoke a LivoxLidarAsyncControlCallback to manage the status centrally?**
