### ISSUE TITLE
Is it possible to install and run Livox SDK1 and Livox SDK2 on the same PC?

### ISSUE THREAD

**Issue by imoted** [Livox-SDK/Livox-SDK2#13]
Is it possible to install and run Livox SDK1 and Livox SDK2 on the same PC?

**Comment by Livox-Infra** [comment]
Yes.
In some scenarios we have to install both Livox SDK1 & Livox SDK2 so that new protocol lidars (such as HAP) and the previous protocol ones (such as Horizon, Avia...) can work together.

**Comment by imoted** [comment]
thank you for your reply!
