### ISSUE TITLE
No response from HAP, sample error

### ISSUE THREAD

**Issue by Minsu-Kim-KNU** [Livox-SDK/Livox-SDK2#3]
Hi all,

I tried to use HAP, but there is no response from HAP.

My error is the figure below, and I already set my IP setting such as

IP : 192.168.1.100
Netmask : 255.255.255.0
Gateway : 192.168.1.1

Any solutions or advices?

Thanks.

![image](https://user-images.githubusercontent.com/97087039/186136004-39865d62-2a2a-4312-8649-6d4f36c30a05.png)

**Comment by JIANever404** [comment]
在config.json里面修改所有IP地址为你的网卡IP

**Comment by Minsu-Kim-KNU** [comment]
@JIANever404 

Hi JIA, 

I already setup my IP address.

Thanks for your reply.
