### ISSUE TITLE
MID 360 LiDAR Integration in ROS2

### ISSUE THREAD

**Issue by Prabuddhi-05** [Livox-SDK/Livox-SDK2#55]
I am currently working on integrating the MID 360 LiDAR into a ROS 2 environment. I have successfully operated the LiDAR with Windows application and ROS1.

Here's a brief overview of my setup and the problem I'm facing:

Setup Details:
Host IP: 192.168.1.50
LiDAR IP: 192.168.1.102

![IPs](https://github.com/Livox-SDK/Livox-SDK2/assets/119497903/8908a02f-7e3a-4b3f-8729-561549666593)

ROS 2 Environment:
OS: Ubuntu 22.04
ROS 2 Distribution: Humble

Software Installation:
Installed Livox SDK 2 from https://github.com/Livox-SDK/Livox-SDK2
Installed livox_ros_driver2 from https://github.com/Livox-SDK/livox_ros_driver2

Configuration:
Edited the IP addresses for both the host and LiDAR in the MID360_config.json file to match the IP settings.

![json_file](https://github.com/Livox-SDK/Livox-SDK2/assets/119497903/c39d2e95-f434-4838-8926-f0a78e320199)

Problem Description:
When I launch the rviz_MID360_launch.py script, which is intended to configure RViz for visualizing LiDAR data, I encounter an issue: the point cloud is not displayed in RViz.

![RVIZ_window](https://github.com/Livox-SDK/Livox-SDK2/assets/119497903/acfe4a92-377d-4788-b6ab-0e1a05728c8e)

I've performed various checks, such as verifying network connectivity, and ensuring the accuracy of the IP configuration. However, I haven't been able to resolve the issue on my own.

**Comment by Prabuddhi-05** [comment]
The issue was resolved by turning off the firewall to ensure that some of the ports were no longer blocked.

**Comment by SurendhranV** [comment]
HI ,
i used livox mid 360 in ros2 humble but getting some error like bind error if anybody know please tell me:
user@user:~/ws_livox/src$ ros2 launch livox_ros_driver2 rviz_MID360_launch.py
[INFO] [launch]: All log files can be found below /home/user/.ros/log/2025-06-10-17-51-59-952149-user-19932
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [livox_ros_driver2_node-1]: process started with pid [19933]
[INFO] [rviz2-2]: process started with pid [19935]
[livox_ros_driver2_node-1] [INFO] [1749558120.043799958] [livox_lidar_publisher]: Livox Ros Driver2 Version: 1.2.4
[livox_ros_driver2_node-1] [INFO] [1749558120.044274461] [livox_lidar_publisher]: Data Source is raw lidar.
[livox_ros_driver2_node-1] [INFO] [1749558120.044300504] [livox_lidar_publisher]: Config file : /home/user/ws_livox/install/livox_ros_driver2/share/livox_ros_driver2/launch_ROS2/../config/MID360_config.json
[livox_ros_driver2_node-1] LdsLidar *GetInstance
[livox_ros_driver2_node-1] config lidar type: 8
[livox_ros_driver2_node-1] successfully parse base config, counts: 1
[livox_ros_driver2_node-1] bind failed
[livox_ros_driver2_node-1] Failed to init livox lidar sdk.
[livox_ros_driver2_node-1] [ERROR] [1749558120.047151608] [livox_lidar_publisher]: Init lds lidar fail!

**Comment by Prabuddhi-05** [comment]
> HI , i used livox mid 360 in ros2 humble but getting some error like bind error if anybody know please tell me: user@user:~/ws_livox/src$ ros2 launch livox_ros_driver2 rviz_MID360_launch.py [INFO] [launch]: All log files can be found below /home/user/.ros/log/2025-06-10-17-51-59-952149-user-19932 [INFO] [launch]: Default logging verbosity is set to INFO [INFO] [livox_ros_driver2_node-1]: process started with pid [19933] [INFO] [rviz2-2]: process started with pid [19935] [livox_ros_driver2_node-1] [INFO] [1749558120.043799958] [livox_lidar_publisher]: Livox Ros Driver2 Version: 1.2.4 [livox_ros_driver2_node-1] [INFO] [1749558120.044274461] [livox_lidar_publisher]: Data Source is raw lidar. [livox_ros_driver2_node-1] [INFO] [1749558120.044300504] [livox_lidar_publisher]: Config file : /home/user/ws_livox/install/livox_ros_driver2/share/livox_ros_driver2/launch_ROS2/../config/MID360_config.json [livox_ros_driver2_node-1] LdsLidar *GetInstance [livox_ros_driver2_node-1] config lidar type: 8 [livox_ros_driver2_node-1] successfully parse base config, counts: 1 [livox_ros_driver2_node-1] bind failed [livox_ros_driver2_node-1] Failed to init livox lidar sdk. [livox_ros_driver2_node-1] [ERROR] [1749558120.047151608] [livox_lidar_publisher]: Init lds lidar fail!

Hi. This error usually happens when the IP address in your **MID360_config.json** doesn’t match your PC’s network interface. Please make sure to set the correct **lidar_ip** corresponding to your machine's IP address that is connected to the Livox sensor.

You can refer to this discussion where a similar issue was resolved:
https://github.com/Livox-SDK/livox_ros_driver2/issues/2

Hope this helps!
