### ISSUE TITLE
[mid360+pps+gprmc] repeating missing pointcloud packets for 40.0 sec in a 100.0s period

### ISSUE THREAD

**Issue by YikangZhang1641** [Livox-SDK/Livox-SDK2#78]
Solved. 
Caused by illegal GPRMC msg.
Nothing wrong with Mid360.

------------------------------------------------------------------------------------------

This happends frequently:

![45](https://github.com/Livox-SDK/Livox-SDK2/assets/37646846/174a15cb-19c2-4c5f-958b-387c0ac719d5)

Before time 45.485, everything's OK. 10Hz Pointcloud and 200Hz IMU are well synchronized.
Something happens. 
After time 45.491, no Pointcloud but only IMU packets are transferred.

Pointcloud packets are resumed at time 85.484
![85](https://github.com/Livox-SDK/Livox-SDK2/assets/37646846/68fc4807-bc8c-4311-8ec0-eaf1bcc96800)

With no hardware changed, the Lidar would be muted for exact 40s and awake for 60s, and then repeats in the next 100s loop: 

At time 145.495, pointclouds start to be missing again
![145](https://github.com/Livox-SDK/Livox-SDK2/assets/37646846/17331727-06ea-4d65-8d16-56a09d64a5cd)

until 185.488
![185](https://github.com/Livox-SDK/Livox-SDK2/assets/37646846/82c792bd-1cc5-4f86-9501-c19d5051099a)

miss at 245.495
![245](https://github.com/Livox-SDK/Livox-SDK2/assets/37646846/70f09038-3c69-4802-9a0c-38d06dbe0cd4)

resume at 285.493
![285](https://github.com/Livox-SDK/Livox-SDK2/assets/37646846/6f016fd0-57a8-41c6-81e0-d2ab384bbec7)

With the PPS/GPRMC cable disconnected, "Time Sync Type" is still "GPS Sync", but everything's fine and continuous. 
However, if reconnected afterwards, pointclouds would be stuck again much longer, sometimes freeze forever.

**Comment by YikangZhang1641** [comment]
Anyone who came from https://github.com/sheng00125/LIV_handhold or https://gitee.com/gwmunan/fast-livo_-reproduction trying to set hardware trigger might face the same problem.
The original GPRMC generating code in Timer.c might work for AVIA but definitely not for mid360. Checksum should be added and global time should be "hhmmss.00" format instead of second counts.

**Comment by leoheung** [comment]
> Anyone who came from https://github.com/sheng00125/LIV_handhold or https://gitee.com/gwmunan/fast-livo_-reproduction trying to set hardware trigger might face the same problem. The original GPRMC generating code in Timer.c might work for AVIA but definitely not for mid360. Checksum should be added and global time should be "hhmmss.00" format instead of second counts.

您好， 请问mid360是否不支持PPS秒脉冲触发？
