### ISSUE TITLE
No source of built-in IMU to LiDAR extrinsics

### ISSUE THREAD

**Issue by Marselka** [Livox-SDK/Livox-SDK2#80]
Could someone prompt where lidar to built-in IMU extrinsics are usually obtained from? I use mid 360, for instance.

User Manual - no info
Livox Viewer 2 - no extrinsics
LiDAR Information Push UDP packets do not have the field with transformation

**Comment by JokerYan** [comment]
The user menu includes the IMU extrinsics.
![image](https://github.com/Livox-SDK/Livox-SDK2/assets/18729314/5630ebf8-fc14-46de-859f-896388976366)

**Comment by Marselka** [comment]
@JokerYan Thanks a lot!

Tech support by email provided also the following, if one interested:

The built-in IMU of the LiDAR is for SMT installation, and the relative value of the installation position is fixed; Hexahedral calibration will be performed at the factory, and this calibration process has been completed. Customers do not need additional IMU calibration and can use it directly.
